[package]
name = "hoplitekb-wasm-rs"
version = "0.1.0"
authors = ["jeremymarch <jmarch@gradcenter.cuny.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2.45"
rustunicodetests = { path = "../rustunicodetests" }
# alloc = "1.28.0"

[lib]
crate-type =["cdylib"]
