[package]
name = "hoplitekb-wasm-rs"
version = "0.2.0"
authors = ["jeremymarch <jmarch@gradcenter.cuny.edu>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2.83"
polytonic-greek = { git = "https://github.com/jeremymarch/polytonic-greek", version = "0.3.2" }

[lib]
crate-type =["cdylib"]

[profile.release]
opt-level = "z"
